[package]
name = "srtemplate"
version = "0.3.3"
edition = "2021"
description = "Template String blazing fast with dependencyless"
categories = ["template-engine", "text-processing"]
keywords = ["runtime", "string", "template"]
authors = ["Sergio Ribera"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/SergioRibera/srtemplate"
homepage = "https://github.com/SergioRibera/srtemplate"
readme = "README.md"
include = ["**/**/*.rs", "Cargo.toml", "rust-toolchain.toml", "rustfmt.toml"]
exclude = ["examples/real_world/"]

[workspace]
members = ["helper_macros"]
exclude = ["examples/real_world"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.bench]
lto = true

[profile.dev]
opt-level = 1
incremental = true

[profile.release]
strip = true
lto = "thin"
panic = 'abort'
opt-level = 3
codegen-units = 1

[features]
default = ["text", "os", "math", "typed_args"]
debug = ["dep:log"]
text = []
os = []
math = ["dep:paste"]
typed_args = []
macros = ["helper_macros"]

[dev-dependencies]
divan = "0.1.14"

[dependencies]
dashmap = "5.5.3"
thiserror = "1.0.49"
paste = { version = "1.0.14", optional = true }
log = { version = "0.4.20", optional = true }
helper_macros = { package = "srtemplate_helper_macros", version = "0.1", path = "helper_macros", optional = true }

[[bench]]
name = "parser"
harness = false

[[example]]
name = "parse_args"
required-features = ["typed_args"]
path = "./examples/parse_args.rs"

[[example]]
name = "macros"
required-features = ["macros"]
path = "./examples/macros.rs"
